dataset-name = "imagenet-1k"
model-name = "resnet18"
model-path = "dataset.models.resnet18.ResNet18"
image-size = 224             # 原始数据集的图片大小是256 * 256，但是后面会处理成224 * 224
num-classes = 1000
num-channels = 3
num-server-rounds = 250        # 服务端训练轮次
fraction-evaluate = 0.0      # 每轮参与评估的客户端比例
local-epochs = 5             # 客户端本地训练轮次（关键参数）
learning-rate = 0.01          # 客户端学习率（关键参数）
batch-size = 32              # 客户端批次大小（关键参数）
alpha = 1.0                  # 迪利克雷分布参数
fraction-fit = 0.5
